server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: customer-service
          uri: lb://service-customer
          predicates:
            - Path=/customers/**
        - id: product-service
          uri: lb://service-product
          predicates:
            - Path=/products/**
        - id: shopping-service
          uri: lb://service-shopping
          predicates:
            - Path=/invoices/**